# Configuration of Hugo
# Guide: https://docs.hugoblox.com/tutorial/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Website name
title: Jiaqi He 
# Website URL
baseURL: 'https://www.he-jiaqi.com/'

############################
## LANGUAGE
############################

defaultContentLanguage: en
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true

############################
## ADVANCED
############################

build:
  writeStats: true
enableGitInfo: false
summaryLength: 30   #Sets the length of the summary for posts or articles to 30 words.
paginate: 10       
enableEmoji: true  #Limits the number of items per page to 10 
enableRobotsTXT: true   #Automatically generates a robots.txt file for your site, which is used by search engines to manage which parts of your site they should crawl.
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]
permalinks:                       #Configures custom URL paths (permalinks) for different content types like event, tags, categories, and publication_types
  authors: '/author/:slug/'
  event: '/talk/:slug/'
  tags: '/tag/:slug/'
  categories: '/category/:slug/'
  publication_types: '/publication-type/:slug/'
disableAliases: true
outputs:
  home: [HTML, RSS, headers, redirects, backlinks]
  section: [HTML, RSS]
imaging:
  resampleFilter: lanczos
  quality: 80
  anchor: smart
timeout: 600000
taxonomies:
  author: authors
  tag: tags
  category: categories
  publication_type: publication_types
markup:
  _merge: deep
related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 70
  #highlight:        
  #  lineNos: false  
security:
  _merge: deep
sitemap:
  _merge: deep
